apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: naaman-jenkins-x
    provider: github
    repository: jenkins-x-qs
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: naaman-jenkins-x-jenkins-x-qs
  namespace: jx
spec:
  httpCloneURL: https://github.com/naaman-jenkins-x/jenkins-x-qs.git
  org: naaman-jenkins-x
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jenkins-x-qs
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/naaman-jenkins-x/jenkins-x-qs
